### ISSUE TITLE
feature request - setter for bin content to handle dynamic heights

### ISSUE THREAD

**Issue by lhluo** [stefanpenner/layout-bin-packer#19]
Hi, i'm currently using your library to lazily-render a list of items, however, some of my items are **expandable**, in which case I have to re-instantiate the bin object with the new array of heights. In particular, I'm using the shelf-first algorithm. Is there any optimization that can be done so that the bin does not have to be re-instantiated?

Thanks for the good work!

**Comment by stefanpenner** [comment]
Quite a late reply, I didn't notice this question... But no time like the present to respond.

If the content array is updated, you can call `.flush(index)`, on your shelf-first instance, where `index` is the elements position where the height changed.

This will:
* preserve state up to that index, as it won't need to be recalculated... Saving otherwise wasted computation.
* discard internal state including and beyond the index, as the this state is now invalid
